import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent } from '@/components/ui/card';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, Legend, } from 'recharts';
export default function CareerJourneyChart({ data }) {
    return (_jsx(Card, { children: _jsxs(CardContent, { className: "p-5", children: [_jsxs("div", { className: "flex justify-between items-center mb-4", children: [_jsx("h2", { className: "text-lg font-semibold font-poppins", children: "Career Journey" }), _jsx("div", { className: "text-sm text-primary", children: _jsxs("select", { className: "border-none bg-transparent focus:outline-none cursor-pointer", children: [_jsx("option", { children: "This Year" }), _jsx("option", { children: "Last Year" }), _jsx("option", { children: "All Time" })] }) })] }), _jsx("div", { className: "h-64", children: _jsx(ResponsiveContainer, { width: "100%", height: "100%", children: _jsxs(BarChart, { data: data, margin: { top: 10, right: 10, left: 10, bottom: 20 }, children: [_jsx(CartesianGrid, { strokeDasharray: "3 3", vertical: false }), _jsx(XAxis, { dataKey: "month", axisLine: false, tickLine: false, fontSize: 12, dy: 10 }), _jsx(YAxis, { axisLine: false, tickLine: false, fontSize: 12, tickFormatter: (value) => `${value} XP` }), _jsx(Tooltip, { formatter: (value) => [`${value} XP`, 'XP Earned'], contentStyle: {
                                        borderRadius: '8px',
                                        border: 'none',
                                        boxShadow: '0 4px 12px rgba(0, 0, 0, 0.08)',
                                    } }), _jsx(Legend, {}), _jsx(Bar, { dataKey: "xp", name: "XP Earned", fill: "hsl(231, 44%, 56%)", radius: [4, 4, 0, 0], barSize: 30 })] }) }) }), _jsxs("div", { className: "flex items-center justify-center mt-4 text-sm", children: [_jsxs("div", { className: "flex items-center mr-4", children: [_jsx("div", { className: "w-3 h-3 bg-primary rounded-full mr-2" }), _jsx("span", { children: "XP Earned" })] }), _jsxs("div", { className: "flex items-center", children: [_jsx("div", { className: "w-3 h-3 bg-[#8bc34a] rounded-full mr-2" }), _jsx("span", { children: "Goals Completed" })] })] })] }) }));
}
