import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useUser } from '@/lib/useUserData';
import { Link } from 'wouter';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Bell, Menu, Search, ShieldAlert } from 'lucide-react';
export default function StaffHeader({ onMenuToggle }) {
    const { user } = useUser();
    return (_jsxs("header", { className: "h-16 border-b bg-white shadow-sm flex items-center justify-between px-4", children: [_jsx("button", { className: "md:hidden flex items-center justify-center h-10 w-10 rounded-md hover:bg-neutral-100", onClick: onMenuToggle, children: _jsx(Menu, { className: "h-5 w-5" }) }), _jsxs("div", { className: "md:hidden flex items-center", children: [_jsx(ShieldAlert, { className: "w-5 h-5 text-primary mr-2" }), _jsx("span", { className: "font-bold text-primary", children: "Staff Portal" })] }), _jsx("div", { className: "hidden md:flex items-center flex-1 ml-4 max-w-md", children: _jsxs("div", { className: "relative w-full", children: [_jsx(Search, { className: "absolute left-2 top-2.5 h-4 w-4 text-muted-foreground" }), _jsx(Input, { placeholder: "Search users, tickets, content...", className: "pl-8 w-full bg-neutral-50 border-neutral-200" })] }) }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsx("div", { className: "relative", children: _jsxs(Button, { variant: "ghost", size: "icon", className: "relative", children: [_jsx(Bell, { className: "h-5 w-5" }), _jsx("span", { className: "absolute -top-1 -right-1 bg-primary text-primary-foreground text-xs font-medium rounded-full h-5 w-5 flex items-center justify-center", children: "3" })] }) }), _jsx("div", { className: "h-8 border-l border-neutral-200" }), _jsxs("div", { className: "flex items-center", children: [_jsxs("div", { className: "mr-3 text-right hidden md:block", children: [_jsx("p", { className: "text-sm font-medium", children: user?.name }), _jsx("p", { className: "text-xs text-muted-foreground capitalize", children: user?.userType })] }), _jsx(Link, { href: "/staff/profile", children: _jsx(Avatar, { className: "h-9 w-9 cursor-pointer", children: user?.profileImage ? (_jsx(AvatarImage, { src: user.profileImage, alt: user.name })) : (_jsx(AvatarFallback, { className: "bg-primary/10 text-primary", children: user?.name.charAt(0) })) }) })] })] })] }));
}
